apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "vote.fullname" . }}
  labels:
    app: {{ template "vote.name" . }}
    chart: {{ template "vote.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vote.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vote.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: OPTION_A
            value: "{{ .Values.vote_options.OPTION_A }}"
          - name: OPTION_B
            value: "{{ .Values.vote_options.OPTION_B }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
  