apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ template "db.name" . }}
    chart: {{ template "db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "db.name" . }}
    release: {{ .Release.Name }}
