apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "redis.name" . }}
    release: {{ .Release.Name }}
