# Default values for db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: postgres
  tag: 9.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
