apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: {{ template "votingapplication.fullname" . }}-vote-redis
  labels:
    app: {{ template "votingapplication.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: usesCreated
  source:
    kind: Deployable
    name: {{ template "votingapplication.fullname" . }}-vote
  destination:
    kind: Deployable
    name: {{ template "votingapplication.fullname" . }}-redis