# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_vote
  tag: before
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 80
  nodePort: 31000
