# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: roitev/vote
  tag: BUILD_VERSION
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  targetPort: 80
  nodePort: 31000

vote_options:
  OPTION_A: cola
  OPTION_B: pepsi
